# Generated by Django 5.1.4 on 2025-07-27 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_cart_product_remove_cart_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_lost', models.DateField()),
                ('location_lost', models.CharField(max_length=100)),
                ('item_category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('stationery', 'Stationery'), ('id_card', 'ID Card'), ('accessories', 'Accessories'), ('others', 'Others')], max_length=50)),
                ('item_description', models.TextField()),
                ('item_photo', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('contact_info', models.CharField(max_length=50)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoundReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finder_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('location_found', models.CharField(max_length=100)),
                ('date_found', models.DateField()),
                ('time_found', models.TimeField()),
                ('found_photo', models.ImageField(blank=True, null=True, upload_to='found_items/')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_reports', to='myapp.lostitem')),
            ],
        ),
    ]
