# Generated by Django 5.1.4 on 2025-07-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_lostitem_foundreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='is_found',
            field=models.BooleanField(default=False),
        ),
    ]
