# Generated by Django 5.1.4 on 2025-07-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_lostitem_is_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='found_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
