# Generated by Django 5.1.4 on 2025-07-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_lostitem_options_lostitem_found_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
